# Generated by Django 2.0.3 on 2020-06-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaoyu', '0002_auto_20200620_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
