# Generated by Django 2.0.3 on 2020-06-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaoyu', '0005_personinfo_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
