# Generated by Django 2.0.3 on 2020-06-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaoyu', '0007_auto_20200622_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='tel',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='personinfonew',
            name='b',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='personinfonew',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personinfonew',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personinfonew',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='personinfonew',
            name='img',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='personinfonew',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personinfonew',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
