# Generated by Django 2.0.3 on 2020-06-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaoyu', '0008_auto_20200622_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personinfo',
            options={'verbose_name_plural': '个人信息'},
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='mail',
            field=models.EmailField(default='123@qq.com', max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='tel',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
    ]
