# Generated by Django 2.0.3 on 2020-06-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaoyu', '0009_auto_20200628_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='学号')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='姓名')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='分数')),
            ],
            options={
                'verbose_name_plural': '学生成绩单',
            },
        ),
    ]
