# Generated by Django 2.0.3 on 2020-06-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaoyu', '0011_card_carddetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='标题名称')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='文件')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文件和图片',
                'verbose_name_plural': '文件和图片',
            },
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': '银行卡', 'verbose_name_plural': '银行卡'},
        ),
        migrations.AlterModelOptions(
            name='carddetail',
            options={'verbose_name': '银行卡详情', 'verbose_name_plural': '银行卡详情'},
        ),
    ]
