# Generated by Django 2.0.3 on 2020-06-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaoyu', '0012_auto_20200629_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='up_file', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='fileimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='up_image', verbose_name='图片'),
        ),
    ]
